"""initial tables

Revision ID: 047c1f9c5a8d
Revises: 
Create Date: 2026-01-12 13:16:24.064971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047c1f9c5a8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('os_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('arp_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mac_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=17), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('next_hop', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('preference', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_table')
    op.drop_table('mac_table')
    op.drop_table('arp_table')
    op.drop_table('devices')
    # ### end Alembic commands ###
