"""cascade delete

Revision ID: 0ac134a1e0e0
Revises: 3caa172f0f95
Create Date: 2026-01-15 18:55:08.814473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac134a1e0e0'
down_revision: Union[str, Sequence[str], None] = '3caa172f0f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mac_table_device_id_fkey'), 'mac_table', type_='foreignkey')
    op.create_foreign_key(None, 'mac_table', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mac_table', type_='foreignkey')
    op.create_foreign_key(op.f('mac_table_device_id_fkey'), 'mac_table', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
