"""Add vendor with server default

Revision ID: 2b32cd7f650f
Revises: 885572ca096c
Create Date: 2026-01-31 19:20:02.990050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b32cd7f650f'
down_revision: Union[str, Sequence[str], None] = '885572ca096c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('vendor', sa.String(length=20), server_default='Generic', nullable=False))
    op.add_column('devices', sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('devices', sa.Column('last_synced', sa.DateTime(), nullable=True))
    op.drop_column('devices', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('brand', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('devices', 'last_synced')
    op.drop_column('devices', 'sync_status')
    op.drop_column('devices', 'vendor')
    # ### end Alembic commands ###
