"""add serial number

Revision ID: 3caa172f0f95
Revises: f25e84127473
Create Date: 2026-01-15 13:54:37.722218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3caa172f0f95'
down_revision: Union[str, Sequence[str], None] = 'f25e84127473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('serialnumber', sa.String(length=20), server_default='XXXXXX', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'serialnumber')
    # ### end Alembic commands ###
