"""ethinterfaces added

Revision ID: 538141b86785
Revises: 1cb4cbcae48d
Create Date: 2026-01-18 13:58:56.706746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538141b86785'
down_revision: Union[str, Sequence[str], None] = '1cb4cbcae48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=50), nullable=False),
    sa.Column('oper_status', sa.String(length=50), nullable=False),
    sa.Column('admin_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('interface_tagness', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interfaces')
    # ### end Alembic commands ###
