"""constaint for eth interface table

Revision ID: 7d1aa5a67f59
Revises: 0ed6160e4046
Create Date: 2026-01-18 16:16:22.104754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1aa5a67f59'
down_revision: Union[str, Sequence[str], None] = '0ed6160e4046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_device_interface', 'eth_interfaces', ['device_id', 'interface_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_interface', 'eth_interfaces', type_='unique')
    # ### end Alembic commands ###
