"""vlan_catalog added

Revision ID: 885572ca096c
Revises: 6d8f94025e68
Create Date: 2026-01-27 11:22:24.494989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885572ca096c'
down_revision: Union[str, Sequence[str], None] = '6d8f94025e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlan_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlan_catalog_id'), 'vlan_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_vlan_catalog_vlan_id'), 'vlan_catalog', ['vlan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlan_catalog_vlan_id'), table_name='vlan_catalog')
    op.drop_index(op.f('ix_vlan_catalog_id'), table_name='vlan_catalog')
    op.drop_table('vlan_catalog')
    # ### end Alembic commands ###
