"""ethinterfaces name changed 2

Revision ID: 99381dfae6fa
Revises: fc20a9bb693e
Create Date: 2026-01-18 15:51:24.666182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99381dfae6fa'
down_revision: Union[str, Sequence[str], None] = 'fc20a9bb693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
