"""ethinterfaces name changed

Revision ID: fc20a9bb693e
Revises: 538141b86785
Create Date: 2026-01-18 14:00:44.904031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc20a9bb693e'
down_revision: Union[str, Sequence[str], None] = '538141b86785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=50), nullable=False),
    sa.Column('oper_status', sa.String(length=50), nullable=False),
    sa.Column('admin_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('interface_tagness', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('interfaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interface_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('oper_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('admin_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('interface_tagness', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('interfaces_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interfaces_pkey'))
    )
    op.drop_table('eth_interfaces')
    # ### end Alembic commands ###
